### ISSUE TITLE
安装文档过时

### ISSUE THREAD

**Issue by yanickxia** [justmemos/memos#40]
按照文档可以运行，但是一直运行在 dev 模式下，看了下代码中的 mode 好像从 env 获取？还有就是当前的 memos_release.db 结构不对，报错是缺少 paasword_hash 列。

**Comment by NoverNobida** [comment]
现在的文档完全是不对的. 有两点,一是他给的memos_release.db不对. docker 里面next标签的镜像用的数据库结构根本不是这个.二是你得通过环境变量定义一个数据库文件存放位置. 因此, 经过我多次试验, 你首先不带任何参数运行起来, 然后再把容器里面的`/usr/local/memos/memos_dev.db`复制出来, 重命名为`memos_release.db`, 放在任意位置, 比如当前文件夹新建一个目录data, 放进去. 然后再通过
```
docker run --name memos --restart always --publish 8080:8080 -v ./data/:/var/opt/memos -e data=/var/opt/memos neosmemo/memos:next
```
启动.
或者参考我的docker-compose.yml
```yml
version: "3"
services:
  memos:
    image: neosmemo/memos:next
    restart: always
    container_name: memos
    user: 1000:1000
    environment:
      - mode=release
      - port=8080
    volumes:
      - ./data/:/var/opt/memos
    ports:
      - "8080:8080"
```
为什么不直接挂载`/usr/local/memos/memos_dev.db`?因为这个容器启动的时候会新建一个数据库,所以就算挂载了也没用.
